services:
  api-animals:
    build: ./api-animals
    ports:
      - "7003:7003"
    networks:
      - pawcare-network

  api-chat:
    build: ./api-chat
    ports:
      - "7004:7004"
    networks:
      - pawcare-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8060:8060"
    networks:
      network:
        ipv4_address: 10.5.0.5


  vetcare-fe:
    build: ./vetcare-fe
    ports:
      - "3000:3000"
    networks:
      - pawcare-network

volumes:
  mysql_data:

networks:
  pawcare-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1