
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
              - TRACE
            allowedHeaders:
              - "*"
            allowCredentials: true
      default-filters:
        - TokenRelay=
      routes:
        - id: api-animals
          uri: http://localhost:7003
          predicates:
            - Path=/api/animals/**,/api/vaccines/**,/websocket/**
        - id: api-chat
          uri: http://localhost:7004
          predicates:
            - Path=/api/chat/**,/api/reviews/**
  security.oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: http://localhost:8080/realms/vetcare/protocol/openid-connect/certs
    client:
      provider:
        keycloak:
          issuer-uri: http://localhost:8080/realms/vetcare
      registration:
        keycloak:
          provider: keycloak
          client-id: api-gateway-client
          client-secret: bxSlVZ5gHeVRjT4iFujFNTuUygFTJzG4
          authorization-grant-type: authorization_code
          scope: openid


  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
keycloak:
  url: http://localhost:8080
  realm: vetcare
  admin:
    username: admin
    password: admin
    client-id: admin-cli
logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE
server:
  port: 8060


realms_master: http://localhost:8080/realms/master/protocol/openid-connect/token
realms_admin: http://localhost:8080/admin/realms/vetcare