server:
  port: 7005
spring:
  application:
    name: api-anamnesis
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/disertatie/protocol/openid-connect/certs

  datasource:
    url: jdbc:mysql://localhost:3306/anamnesis_api
    username: root
    password: dana
    jpa:
      hibernate:
        ddl-auto: validate

animal:
  service:
    url: http://localhost:7003/api/animals
