server:
  port: 7003
spring:
  application:
    name: api-animals
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://172.31.31.52:8080/realms/pawcare/protocol/openid-connect/certs

  datasource:
    url: jdbc:mysql://pawcare-db.cbymoe2yia17.eu-north-1.rds.amazonaws.com:3306/animal_api
    username: admin
    password: A6kS3IEZW7XH31aqcMFH
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #     ddl-auto: create
  flyway:
    driver-class-name: com.mysql.cj.jdbc.Driver
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  cloud:
    aws:
      credentials:
        access-key: AKIAQGYBPSMFRKWHGKVR
        secret-key: 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
      region:
        static: eu-north-1

logging.level:
  #  org.springframework.cloud.gateway: DEBUG
  #  org.springframework.security: DEBUG
  #  org.springframework.web.reactive.function.client: TRACE
  org.flywaydb.core: DEBUG
  # API Keys (external services)
dog:
  api:
    key: live_RbE6Q73mvZcPNpCsClhTZBRg5GpjDSJt0VRWTe1icJb9C7JuFg0qXpBuP8DNA2e6

cat:
  api:
    key: live_YFZijdMlfnpNqm7HbT7xgT6K05OLrjB4pvQQQDQxAkMsLsfop75humT7nS4YQp3I
